# Generated by Django 5.2 on 2025-04-26 07:35

import phones.lib.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Datetime of action')),
                ('action', models.CharField(max_length=255, verbose_name='What the action')),
                ('log', models.TextField(blank=True, null=True, verbose_name='Result of action')),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=16, validators=[phones.lib.validators.validate_phone_rus])),
            ],
        ),
    ]
