# Generated by Django 5.2 on 2025-04-29 22:47

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_registryfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DEFPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avs', models.IntegerField()),
                ('start', models.IntegerField()),
                ('to', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('operator', models.TextField()),
                ('region', models.CharField(max_length=255)),
                ('territory', models.CharField(max_length=255)),
                ('inn', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='registryfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='tmp/registry'), upload_to=''),
        ),
    ]
