# Generated by Django 5.2 on 2025-05-01 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_defphone_alter_registryfile_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defphone',
            options={'ordering': ['-avs'], 'verbose_name': 'DEFPhone', 'verbose_name_plural': 'DEFPhones'},
        ),
    ]
